name: flutter_utils
description: A new Flutter package project.
version: 0.0.2
homepage: sisitech.com

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  get: ^4.6.5
  intl: ^0.18.0
  flutter:
    sdk: flutter

  fl_chart: ^0.61.0
  url_launcher: ^6.1.10
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.7.0
  get_storage: ^2.0.3
  slugify: ^2.0.0
  workmanager: ^0.5.1
  package_info_plus: ^5.0.1
  flutter_local_notifications: ^13.0.0
  mixpanel_flutter: ^2.2.0
  nfc_manager: ^3.4.0
  flex_color_scheme: ^7.3.1
  reactive_forms: ^14.1.0
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  encrypt: ^5.0.1
  crypto: ^3.0.1
  font_awesome_flutter: ^10.7.0
  flutter_screen_lock: ^9.0.4
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  flutter_auth:
    git:
      url: git@github.com:sisitech/flutter_auth.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  lottie: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/loading-animation.json

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
