import 'package:get/get.dart';

const translationKeys = {
  'en_US': {
    'hello': 'Hello World',
    'Add': 'Add',
    'empty_field': "This field must not be empty"
  },
  'so_SO': {
    "Proceed with your ": "sii wad",
    "Login": "Gal",
    "School Code / Phone Number ": "Nambarka/Telefanka iskuulka",
    "Password": "Furaha sirta ah",
    "Forgot Password": "Hilmaamey Furaha sirta ah",
    "Authenticating": "Xaqiijinta",
    "Mark Attendance": "Xaadiri",
    "Showing attendance for": "Tusinaya Xaadirinta",
    "Submit": "Gudbi",
    "Class": "Fasalka",
    "Attendance": "Xaadirin",
    "My School": "Iskuulkayga",
    "Reports": "Warbixino",
    "Profile": "Astaanta Shaqsi",
    "Take attendance": "Xaadiri",
    "Take class 1 attendance with 7 students absent on ":
        "Qaad Xaadirinta Fasalka Kowaad oo 7 arday maqantahay",
    "Cancel": "Baaji",
    "Yes": "Haa",
    "Okay": "Hagaag",
    "Submitting attendance": "Gudbinaya xaadirin",
    "Present Students": "Ardayda Xaadirka ah",
    "Absent Students": "Ardayda maqan",
    "Thank you, ": "Mahadsanid",
    "Daily attendance report": "Warbixinta Xaadirinta Maalinlaha ah",
    "Students Present": "Ardayda Xaadirka ah",
    "Total number of present students in the class today":
        "Wadarta Guud ee ardayda xaadirka ah maanta",
    "Students Absent": "Ardayda Maqan",
    "Total number of absent students in the class today":
        "Wadarta guud ee ardayda maqan maanta",
    "Students": "Arday",
    "Boys": "Wiilal",
    "Girls": "Gabdho",
    "Total Students": "Ardayda Guud",
    "Add / Edit Students": "Kudar/tafatir ardayda",
    "View student details": "Eeg Faahfaahinta Ardayda",
    "Move students": "Guuri ardayda",
    "Promote Students": "Dalacsii Ardayda",
    "Teachers": "Macalimiinta",
    "Add / Edit Teachers": "Kudar/tafatir Macalimiinta",
    "Classes": "Fasalada",
    "Add / Edit Classes": "Kudar/Tafatir Fasalada",
    "Boys Present": "Wiilasha Xaadirka ah",
    "Girls Present": "Gabdhaha Xaadirka ah",
    "Boys Absent": "Wiilasha maqan",
    "Girls Absent": "Gabdhaha Maqan",
    "View Absent Students List": "Eeg liiska ardada Maqan",
    "User Profile": "Astaanta isticmaalaha",
    "Edit Password": "Tafatir Furaha sirta ah",
    "Applications Settings": "Dejinta Ablikeeshanada",
    "Attendance Status": "Xaalada xaadirinta",
    "Update student list ": "Cusboonaysii Liiska Ardayda",
    "Help & User Manual": "Buuga Caawinaada Isticmaalaha",
    "Logout": "Kabax",
    "Old Password": "Furaha sirta ah ee Duugoobay",
    "New Password": "Furaha sirta ah ee cusub",
    "Confirm Password": "Xaqiiji Furaha sirta ah",
    "Change Password": "badel Furaha sirta ah",
    "Loading": "soo kacayaa",
    "Internet Status": "Xaalada internetka",
    "Connected": "ku xidhan",
    "Disconnected": "aan Ku xidhnayn",
    "Last Upload Date": "Taarikhda ugu danbaysay ee Gelinta",
    "Records saved offline": "Rikoodhka kaydsan Khad laan",
    "Items Failed to Upload": "shayada soo Kici waayey",
    "Download Latest Class List": "Soo Dajiso liiska Ardayda ee ugu Danbeeyey",
    "Updating ": "cusbooneysiinaya",
    "Success": "Guuleystay",
    "Class list updated successfully":
        "Waa lagu guulaysatay cusboonaysiinta liiska ardayda",
    "Help & Support": "Caawinaad iyo Taageero",
    "Is my phone's Android version suitable with this mobile application?":
        "Teleefankayga noocan Androidka ah ma ku haboonyahay Barnaamijkan?",
    "The mobile application works for Android 4.4 and above":
        "Barnaamijkan Mobilka wuxuu ku shaqeeya Android 4.4 iyo wixi ka sareeya",
    "How long does data stay on my phone in offline mode until it is submitted to the server?":
        "Ilaa intee in leeg ayay xogta ku kaydsanaan kartaa mobilkayga khad laan kahor intaan Saafarka loo gudbin?",
    "The mobile application saves your offline data for upto 30 days before it is submitted to our server. Submission occurs automatically when you access an internet connection":
        "Barnaamijkan Mobilka wuxuu kaydinayaa xogtaada 30 beri kahor inta uusan saafarka u gudbin wuxuu saafarka u gudbinaaya goortaad khad interneet aad hesho si iskii ah",
    "Another teacher has added new students to my classroom but I cannot see them on the list on my phone, what should I do?":
        "Macalin kale baa wuxuu arday cusub ku daray fasalkayga lakin kumaarko iyaga liiskooda mobilkayga,Maxaan sameeyaa?",
    "We handle updating of student class list automatically, however, incase you do not see your student list, navigate to Profile > Update Student List and click on Download Latest Class list button":
        "Waxaan u samaynaa cusboonaysiinta Liiska ardayada si iskeed ah,balse hadii ad arki weydo liiska ardaydaada waxaad aada qeqybta Profile>Update Students list kadibne kudhufo download latest class list button",
    "Are updates to this mobile application automatic?":
        "Cusboonaysiinta barnaamijkan Mobeelka ah ma si iskeed ah baa?",
    "Yes, updates to the mobile application submitted by our developer team are automatically handled by Google's PlayStore":
        "Haa,cusboonaysiinta barnaamijka mobeelka ee uu soo gudbiyeen kooxdeena barnaamijyada soo saara waxaa si iskeed ah u qabata Google Play Store",
    "I have an inquiry, how do I contact the support team ?":
        "Waxaan Qabaa Suaal,sideen ula xiriiraa Kooxda Taagerada Barnaamijkan",
    "Incase you need to get in touch, email our support team at support@wvsomdigital.org":
        "Lacala hadii aad nagu soo xidhanto iimail usoo dir support@wvsomdigital.org",
    "Incase you need further assistance, kinldy refer to our user manual below":
        "Lacala hadii aad u baahantahay caawinaad dheeri ah,Fadlan eeg buugeena isticmaalka barnaamijkan",
    "Download User Manual": "soo Dajiso buuga isticmaalka",
    "": "",
    "Your Classes": "Fasaladiina",
    "Delete": "Tir",
    "Search": "Raadi",
    "Select Reason To Delete Student": "Dooro sababta loo tirayo ardayga",
    "Please select a reason": "Fadlan dooro sababta",
    "Please provide a reason": "Fadlan sheeg sababta",
    "You must be online to delete a student":
        "Waa inaad khad internet haysataa si ad u tirto arday",
    "No classes available offline": "Majiraan Fasalo Khad internet laan",
    "This class has no students": "Fasalkan malahan arday",
    "Please fill in all the fields": "Fadlan buuxi meelaha banaan",
    "You are offline. Can edit only when Online":
        "Waxaad tahay Khad internet laan.waxan tafatiri kartaa goortaad khad internet hesho",
    "Student details successfully Updated":
        "waa lagu guuleystay in xogta ardayda la cusboonaysiiyo",
    "An Error Occured. Please Try Again Later":
        "Khalad baa dhacay.Fadlan isku day mar kale",
    "Student added successfully": "waa lagu guulaystay in ardayga lagu daray",
    "student will be created when you get online":
        "Liiska ardayda way soo galayaan markaad khad internt hesho",
    "Data will be synced when you get online":
        "Xogta wey iswareejinaysaa markaad khadka internetka gashid",
    "Provide Reason for Absence": "Sheeg sababta maqnaanshaha",
    "Sync students data to Database": "Kuwareeji xogta ardayda kaydka Xogta",
    "Enter Stream Name": "Gali qulqulka magacyada ardada",
    "Stream Name": "Magaca qulquka ardada",
    "Class Already Exists": "Fasalkan horeyba u jiray",
    "All Classes / Students / teachers":
        "Fasaladoo dhan/ardado dhan/Macaliimiinta",
    "promote to ": "U dalacsii",
    "reverse promotion": "Kanoqo dalacsiinta",
    "complete promotion": "Dhamaystri dalacsiinta",
    "Attendance for this date was not taken": "Xaadirinta malintan lama sameyn",
    "View Attendance Chart": "Eeg shaxanka xaadirinta",
    "Error": "Khalad",
    "Update Reason for Absence": "Cusboonaysii sababta maqnaanshaha",
    "Move students to class?": "Kuwareeji ardayda fasal?",
    "Select at least one student!": "Dooro ugu yaraan hal arday!",
    "Select which class to move students to!":
        "Dooro fasalka ardayda loo wareejinayo",
    "Contact Not Found": "Xiriirka lama helin",
    "Please update guardian contact information!":
        "Fadlan cusboonaysii masuulka xogta lagala xiriirayo",
    "Place a call to John guardian?": "Wac waalika John?",
    "Call Guardian": "Wac waalidka",
    "Attendance Report": "Warbixinta xaadirinta",
    "You can't perform this operation offline":
        "Ma fulin kartid adeegan khad internet laan",
    "Promote Class": "Dalacsii Fasal",
    "Change Language": "Badel luuqada",
    "Select Language": "Dooro Luuqad",
    "Delete John": "Tir John",
    "Weekly Attendance Chart": "Shaxanka Xaadirinta ee asbuuclaha",
    "Retention Rate": "Heerka Haynta",
    "This is the probability calculated by number of days the  student has appeared present":
        "Tan waa itimaalka la xisaabiyey ee tirada maalmaha ardayga uu umuuqdo xadiir",
    "Dropout Rate": "Heerka kabixitaanka",
    "Username and Password didn't match":
        "Magaca isticmaalaha iyo Furaha sirta ah is ma waafaqsana",
    "This is the risk of this student dropping out based on absent days":
        "Tan waa khatarta ardaygan inuu kaharo waxbarashada marka loo eego maalmihiisa maqnaanshaha",
    "First Name": "Magaca u hore",
    "Middle Name": "Magaca Dhexe",
    "Last Name": "Magaca u danbeeya",
    "Admission Number": "Nambarka Qaabilitaanka",
    "Guardian Phone Number": "Telefan nambarka waalidka",
    "Gender": "Jinsiga",
    "Male": "Rag",
    "Female": "Dumar",
    "Select Gender": "Dooro Jinsiga",
    "Date Of Birth": "Taarikhda dhalashada",
    "Select Date": "Dooro Taarikhda",
    "Special Needs": "Baahi Khaas ah",
    "Student Special Needs": "Ardayga leh baahida Khaaska ah",
    "Student Status": "Xaalada ardayga",
    "Select Status": "Dooro xaalada",
    "Guardian Status": "Xaalada waalidka",
    "Select Guardian Status": "Dooro xaalada waalidka",
    "Telephone Number": "Telefan nambarka ",
    "Qualifications": "Aqoonta",
    "University": "Jaamacad",
    "College": "Machad",
    "Select Teacher Qualifications": "Dooro aqoonta macalinka",
    "Select Class / Classes": "Dooro fasal/fasalo",
    "Marital Status": "Xaalada guur",
    "Select Marital Status": "Dooro xaalada guur",
    "Email Adress": "Cinwaanka iimailka",
    "Add as Admin": "Ku dar admin ahaan",
    "Stream already exists": "Qulqulkan horey buu u jiray"
  },
  'ki_KE': {
    "Proceed with": "Thiī na mbere na",
    "Login": "Kuingīra",
    'Submit': 'Tuma',
    "Username": "Rītwa ria kuingira",
    "Delete class @class_name#": "Tharia kirathi kia @class_name#",
    "Password": "Rītwa ya Hitho",
    "Forgot Password": "Nī Uriganīirwo Rītwa ya Hitho",
    "Class @class_name#": "Kīrathi kīa @class_name#",
    "Showing Class List For": "Īronania kīrathi kia",
    "Attendance": "Ūki wa arutwo",
    "Update attendance": "Cenjia Ūki wa arutwo",
    "Taking attendance": "Ndīroya ūki wa arutwo",
    "Select Attendance Date": "Sagūra muthenya wa ūki",
    "Close": "Hinga",
    "Confirm": "Nī ndetīkīra",
    "Enter valid date": "Ihūria muthenya wa ma",
    "Enter valid date range": "Ihūria mithenya ya ma",
    "Month/Date/Year": "Mweri/Muthenya/Mwaka",
    "Take attendance for @class_name with @present learners present and @absent learners absent on @date#.":
        "Oya ūki wa atuwo a kirathi kia @class_name#, arutwo  @present mokīte na arutwo @absent matokite muthenya wa @date#.",
    "Take": "Oya",
    "Cancel": "Kanja",
    "Submitting...": "Nī gutuma iīratuma...",
    "Take Attendance": "Oya ūki wa arutwo",
    "Mark Attendance": "Maka ūki wa arutwo",
    "Classes": "Irathi",
    "Daily Attendance Report": "Rifoti ya ūki kimūthenya",
    "Thank you, @first_name# @last_name#":
        "Niwega muno,  @first_name# @last_name#",
    "Absent Learners": "Arutwo matokīte",
    "Present Learners": "Arutwo mokīte",
    "Update Reasons For Absence": "Cenjia itūmi cia arutwo gutīra",
    "Present Boys @present_males \nPresent Girls @present_females#":
        "Anake mokīte nī @present_males# \nAirītu mokīte nī @present_females#",
    "Absent Boys @absent_males \nAbsent Girls @absent_females#":
        "Anake matokīte nī @absent_males \nAirītu matokīte @absent_females#",
    "@present_males Present Males": "@present_males Anake mokīte",
    "@absent_males Absent Males": "@absent_males Anake matokīte",
    "@present_females Present Females": "@present_females Airītu mokīte",
    "@absent_females Absent Females": "@absent_females Airītu matokīte",
    "My School": "Thukuru Yakwa",
    "Reports": "Rifoti",
    "Profile": "Ũtuĩria",
    "Learners": "Arutwo",
    "@males Males | @females Females | @total Total Learners":
        "Anake @males | Airitu @females | Arutwo othe ni @total#",
    "Teachers": "Arutani",
    "@classes Total Classes": "Irathi ciothe ni @classes#",
    "@teachers Total Teachers": "Arutani othe ni @teachers#",
    "Move Learners": "Thamia Arutwo",
    "Promote Learners": "Thongia Arutwo",
    "Add / Edit Learners": "Ongerera / Cenjia Arutwo",
    "Deactivated Learners": "Arutwo Matigithītyo",
    "Add / Edit Teachers": "Ongerera / Cenjia Arutani",
    "Add / Edit Classes": "Ongerera / Cenjia Irathi",
    "Search Learner by Name": "Etha mūrutwo na rītwa",
    "This class has no learners": "Kīrathi gīkī gītirī na arutwo",
    "Over Age": "Mūkūrū muno",
    "Never Enrolled": "Ndarī akinya thukuru",
    "Re Enrolled": "Kwandīkithio rīngī",
    "MALE": "Mūndūrūme",
    "FEMALE": "Mūirītu",
    "Yes": "īī",
    "No": "Aca",
    "First Name": "Rītwa Rīambere",
    "Middle Name": "Rītwa rīa Gatagatī",
    "Last Name": "Rītwa rīa mūico",
    "Admission Number": "Namba ya Kwandikithio",
    "Street Name": "Rītwa rīa karenji",
    "Select": "Cagūra",
    "Continue": "Thiī na mbere",
    "Gender": "Mūirītu / Mūndūrūme",
    "Date Of Birth": "Muthenya wa Guciarwo",
    "Date Enrolled": "Muthenya wa kwandīkithio",
    "Does the Learner have any Special Needs?":
        "Mūrutwo ena mabataro ma mwanya?",
    "Has attended Pre-Primary?": "Mūrutwo ni athomete natharī",
    "Region": "Gĩcigo",
    "District": "Itũũra",
    "Vilage": "Gīcagi",
    "Class": "Kīrathi",
    "House Number": "Namba ya Nyumba",
    "Learner Details": "Ūhoro Makĩria wa Murutwo"
  },
  'swa_KE': {
    'hello': 'Habari Yako',
    "Edit Password": "Badilisha neno siri",
    "Offline Attendance Status": "Offline Attendance Status",
    'Add': 'Ongeza',
    'Login': 'Ingia',
    "Profile": 'Mimi',
    "Class @class_name#": "Darasa @class_name#",
    'Submit': 'Wasilisha',
    'Delete ?': 'Futa ?',
    'Delete': 'Futa',
    'Cancel': 'Wacha',
    'Signing in...': 'Naingia...',
    'Contact name': 'Jina la mhusika',
    'Name': 'Jina',
    "Delete shop @name# ?": "Futa duka @name# ?",
    'Teacher Type': 'Cheo cha Mwalimu',
    'Username': 'Kitambulisho',
    'Active': 'Inatumika',
    "TSC": "tsc",
    "Managed by @contact_name#": "Inatunzwa na @contact_name#",
    "Shop's name @name#": "Jina la Duka ni @name#",
    'hello_one': 'habari @name @age 1',
    "empty_field": "Linahitajika",
    "Faield..": "Imefeli..",
    'Modified': 'Ilibadilishwa Lini',
    'Password': 'Neno Siri',
    'School emis Code / Phone number': 'Kodi ya Shule / Nambari ya simu',
  },
  'de_DE': {
    'hello': 'Hallo Welt',
  }
};

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => translationKeys;
}
